Update custom-resource.md
T-Systems-MMS/cmcc-operator pull request #26
Opened 2022-04-22 09:03 UTC by hegessne

i guess mcaefeeder means mls-caefeeder and on master-live-server there is live caefeeder.
preview is located on content-management-server.

2022-04-25 10:58 UTC, stefanbethke requested changes

2022-04-25 10:58 UTC, stefanbethke commented on docs/custom-resource.md
> +| `cae-feeder`/`preview` | `caefeeder`   | `blueprint` | `preview` | `webserver` |             |
Thanks for the correction. Would you mind swapping the two lines, so the entries in the table are all in alphabetical order?

2022-04-25 10:58 UTC, stefanbethke commented on docs/custom-resource.md
> +The Solr collection is `studio`.
This is a stray change of whitespace?

2022-04-26 09:03 UTC, stefanbethke commented
Implemented through https://github.com/T-Systems-MMS/cmcc-operator/commit/e61aa397296f037c9477d7a825993ce4ebe014d8.

2022-04-26 09:03 UTC, closed without merging

2022-04-26 09:06 UTC, hegessne commented
Thanks!